workflows:
  sample-workflow:
    name: Sample Workflow
    max_build_duration: 60
    working_directory: Boaster
    environment:
      flutter: stable
    scripts:
      - name: Get Flutter packages
        script: flutter packages pub get
        
